"""Tests for tools/extract_profile_from_gcode.py.

The extract tool turns a successful G-code into two JSON profiles. The
critical invariants:

- It parses real OrcaSlicer-style `; key = value` metadata
- It emits process scalars and filament lists (Snapmaker Orca's shape)
- first_layer_temperature → nozzle_temperature_initial_layer fallback works
- It handles G-code that's missing metadata gracefully (exit 3, not crash)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

# Make tools/ importable
TOOLS_DIR = Path(__file__).resolve().parent.parent / "tools"
sys.path.insert(0, str(TOOLS_DIR))

import extract_profile_from_gcode as epfg  # noqa: E402


SAMPLE_GCODE = b"""; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4
; HEADER_BLOCK_END

; filament_type = PETG
; filament_vendor = Generic
; filament_settings_id = Community Generic PETG @Snapmaker U1 Textured PEI
; filament_diameter = 1.75
; nozzle_temperature = 240
; nozzle_temperature_initial_layer = 240
; first_layer_temperature = 240
; hot_plate_temp = 80
; textured_plate_temp = 80
; cool_plate_temp = 80
; first_layer_bed_temperature = 80
; layer_height = 0.20
; first_layer_height = 0.20
; wall_loops = 6
; wall_generator = arachne
; sparse_infill_density = 25%
; sparse_infill_pattern = crosshatch
; enable_support = 0
; curr_bed_type = Textured PEI Plate
; nozzle_diameter = 0.4
; print_settings_id = Community 0.20 Strength @Snapmaker U1 Textured PEI

T1
G28
G1 X100 Y100 Z5 F3000
"""


# ---------- parse_gcode_metadata ----------

def test_parse_metadata_extracts_filament_type(tmp_path):
    g = tmp_path / "sample.gcode"
    g.write_bytes(SAMPLE_GCODE)
    meta = epfg.parse_gcode_metadata(g)
    assert meta["filament_type"] == "PETG"
    assert meta["layer_height"] == "0.20"
    assert meta["wall_loops"] == "6"
    assert meta["sparse_infill_density"] == "25%"


def test_parse_metadata_handles_missing_block(tmp_path):
    g = tmp_path / "bare.gcode"
    g.write_bytes(b"G28\nG1 X100 Y100 F3000\n")
    meta = epfg.parse_gcode_metadata(g)
    assert meta == {}


def test_parse_metadata_handles_huge_files(tmp_path):
    """Slicer metadata in the head must survive a megabyte of motion in the middle."""
    g = tmp_path / "huge.gcode"
    g.write_bytes(SAMPLE_GCODE + b"\n" + (b"G1 X1 Y1\n" * 100_000))
    meta = epfg.parse_gcode_metadata(g)
    assert meta["filament_type"] == "PETG"
    assert meta["layer_height"] == "0.20"


# ---------- build_process_profile ----------

def test_process_profile_has_required_shape():
    meta = {
        "layer_height": "0.20",
        "wall_loops": "6",
        "sparse_infill_density": "25%",
        "sparse_infill_pattern": "crosshatch",
        "enable_support": "0",
        "curr_bed_type": "Textured PEI Plate",
        "wall_generator": "arachne",
        "nozzle_diameter": "0.4",
    }
    p = epfg.build_process_profile(meta, "Test Process", "Snapmaker U1 (0.4 nozzle)")
    assert p["type"] == "process"
    assert p["name"] == "Test Process"
    assert p["from"] == "user"
    assert p["inherits"] == ""
    assert p["compatible_printers"] == ["Snapmaker U1 (0.4 nozzle)"]
    assert p["print_settings_id"] == "Test Process"
    assert p["layer_height"] == "0.20"
    assert p["wall_loops"] == "6"
    assert p["sparse_infill_pattern"] == "crosshatch"
    assert p["curr_bed_type"] == "Textured PEI Plate"


def test_process_profile_omits_missing_keys():
    """Metadata that wasn't in the G-code shouldn't produce default-valued fields."""
    p = epfg.build_process_profile({"layer_height": "0.16"}, "Slim Process", "Snapmaker U1 (0.4 nozzle)")
    assert "layer_height" in p
    assert "wall_loops" not in p
    assert "sparse_infill_density" not in p


# ---------- build_filament_profile ----------

def test_filament_profile_uses_list_shape():
    """Snapmaker Orca filament profiles store scalars as single-item lists."""
    meta = {
        "filament_type": "PETG",
        "filament_vendor": "Generic",
        "nozzle_temperature": "240",
        "nozzle_temperature_initial_layer": "240",
        "hot_plate_temp": "80",
        "textured_plate_temp": "80",
    }
    f = epfg.build_filament_profile(meta, "Test Filament", "Snapmaker U1 (0.4 nozzle)")
    assert f["type"] == "filament"
    assert f["filament_type"] == ["PETG"]
    assert f["nozzle_temperature"] == ["240"]
    assert f["filament_settings_id"] == ["Test Filament"]
    assert f["compatible_printers"] == ["Snapmaker U1 (0.4 nozzle)"]
    assert f["filament_diameter"] == ["1.75"]


def test_filament_profile_first_layer_temperature_fallback():
    """If no nozzle_temperature_initial_layer, fall back to first_layer_temperature."""
    meta = {
        "filament_type": "PETG",
        "first_layer_temperature": "245",
        "nozzle_temperature": "240",
    }
    f = epfg.build_filament_profile(meta, "Fallback Test", "Snapmaker U1 (0.4 nozzle)")
    assert f["nozzle_temperature_initial_layer"] == ["245"]
    assert f["nozzle_temperature"] == ["240"]


def test_filament_profile_first_layer_bed_temp_routed_by_bed_type():
    """first_layer_bed_temperature should attach to the active bed type's *_initial_layer."""
    meta = {
        "filament_type": "PETG",
        "curr_bed_type": "Textured PEI Plate",
        "first_layer_bed_temperature": "82",
    }
    f = epfg.build_filament_profile(meta, "Bed Routing", "Snapmaker U1 (0.4 nozzle)")
    assert f["textured_plate_temp_initial_layer"] == ["82"]
    assert "hot_plate_temp_initial_layer" not in f


def test_filament_profile_vendor_override():
    """--vendor on CLI should override 'Generic' from G-code metadata."""
    meta = {"filament_type": "PETG", "filament_vendor": "Generic"}
    f = epfg.build_filament_profile(meta, "Vendor Override", "Snapmaker U1 (0.4 nozzle)", vendor="SUNLU")
    assert f["filament_vendor"] == ["SUNLU"]


# ---------- main() CLI ----------

def test_main_writes_both_profiles(tmp_path, capsys):
    g = tmp_path / "good_print.gcode"
    g.write_bytes(SAMPLE_GCODE)
    process_out = tmp_path / "process.json"
    filament_out = tmp_path / "filament.json"
    rc = epfg.main([
        str(g),
        "--process-out", str(process_out),
        "--filament-out", str(filament_out),
        "--process-name", "Extracted 0.20 PETG",
        "--filament-name", "Extracted PETG SUNLU",
        "--vendor", "SUNLU",
    ])
    assert rc == 0
    assert process_out.exists()
    assert filament_out.exists()
    p = json.loads(process_out.read_text())
    f = json.loads(filament_out.read_text())
    assert p["type"] == "process"
    assert p["name"] == "Extracted 0.20 PETG"
    assert p["layer_height"] == "0.20"
    assert f["type"] == "filament"
    assert f["filament_vendor"] == ["SUNLU"]
    assert f["nozzle_temperature"] == ["240"]


def test_main_missing_gcode_returns_2(tmp_path, capsys):
    rc = epfg.main([str(tmp_path / "nonexistent.gcode")])
    assert rc == 2


def test_main_metadata_only_dumps_raw_keys(tmp_path, capsys):
    g = tmp_path / "good.gcode"
    g.write_bytes(SAMPLE_GCODE)
    rc = epfg.main([str(g), "--metadata-only"])
    captured = capsys.readouterr()
    assert rc == 0
    parsed = json.loads(captured.out)
    assert parsed["filament_type"] == "PETG"
    assert parsed["wall_loops"] == "6"


def test_main_bare_gcode_returns_3(tmp_path):
    g = tmp_path / "bare.gcode"
    g.write_bytes(b"G28\nG1 X10 Y10\n")
    rc = epfg.main([str(g)])
    assert rc == 3


def test_main_brand_label_appended(tmp_path):
    g = tmp_path / "good.gcode"
    g.write_bytes(SAMPLE_GCODE)
    process_out = tmp_path / "p.json"
    filament_out = tmp_path / "f.json"
    rc = epfg.main([
        str(g),
        "--process-out", str(process_out),
        "--filament-out", str(filament_out),
        "--filament-name", "My Generic PETG",
        "--brand-label", "SUNLU Black",
    ])
    assert rc == 0
    f = json.loads(filament_out.read_text())
    assert "SUNLU Black" in f["name"]


# ---------- regression tests for codex-review findings ----------

# Realistic Orca metadata block — same key family on several lines (range_high,
# range_low, _initial_layer) — exercises the prefix-collision case that the
# original parser silently failed on.
REAL_ORCA_GCODE = b"""; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4
; HEADER_BLOCK_END

; nozzle_temperature = 255
; nozzle_temperature_initial_layer = 255
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 230
; hot_plate_temp = 80
; hot_plate_temp_initial_layer = 80
; textured_plate_temp = 80
; textured_plate_temp_initial_layer = 80
; cool_plate_temp = 80
; cool_plate_temp_initial_layer = 80
; filament_settings_id = "My PETG @Snapmaker U1 Textured PEI"
; filament_type = PETG
; nozzle_diameter = 0.4,0.4,0.4,0.4
; layer_height = 0.16
; curr_bed_type = Textured PEI Plate
; print_settings_id = My 0.16 Optimal @Snapmaker U1 Textured PEI

T1
G28
"""


def test_prefix_collision_does_not_overwrite_real_nozzle_temperature(tmp_path):
    """nozzle_temperature must NOT be overwritten by nozzle_temperature_range_low."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_ORCA_GCODE)
    meta = epfg.parse_gcode_metadata(g)
    assert meta["nozzle_temperature"] == "255", \
        f"prefix bug: nozzle_temperature got value from a longer key: {meta['nozzle_temperature']}"
    assert meta["nozzle_temperature_initial_layer"] == "255"


def test_prefix_collision_isolates_plate_temps(tmp_path):
    """*_plate_temp_initial_layer must not poison *_plate_temp."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_ORCA_GCODE)
    meta = epfg.parse_gcode_metadata(g)
    assert meta["hot_plate_temp"] == "80"
    assert meta["hot_plate_temp_initial_layer"] == "80"
    assert meta["textured_plate_temp"] == "80"
    assert meta["textured_plate_temp_initial_layer"] == "80"


def test_quoted_value_strips_outer_quotes(tmp_path):
    """Orca quotes values containing spaces — the quotes must not survive into the dict."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_ORCA_GCODE)
    meta = epfg.parse_gcode_metadata(g)
    assert meta["filament_settings_id"] == "My PETG @Snapmaker U1 Textured PEI"
    assert '"' not in meta["filament_settings_id"]


def test_multi_extruder_nozzle_diameter_csv_collapses_to_first(tmp_path):
    """Multi-tool G-code emits nozzle_diameter = '0.4,0.4,0.4,0.4'; profile wants '0.4'."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_ORCA_GCODE)
    meta = epfg.parse_gcode_metadata(g)
    p = epfg.build_process_profile(meta, "Test", "Snapmaker U1 (0.4 nozzle)")
    assert p["nozzle_diameter"] == "0.4"


def test_main_rejects_non_gcode_suffix(tmp_path, capsys):
    """notes.txt is not a G-code file — bail early with a clear message."""
    bad = tmp_path / "notes.txt"
    bad.write_bytes(b"some text\n")
    rc = epfg.main([str(bad)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "non-G-code" in err or "Refusing" in err


def test_real_world_gcode_end_to_end(tmp_path):
    """All HIGH bugs together: realistic input produces a clean process+filament pair."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_ORCA_GCODE)
    process_out = tmp_path / "p.json"
    filament_out = tmp_path / "f.json"
    rc = epfg.main([
        str(g),
        "--process-out", str(process_out),
        "--filament-out", str(filament_out),
        "--vendor", "SUNLU",
    ])
    assert rc == 0
    p = json.loads(process_out.read_text())
    f = json.loads(filament_out.read_text())
    # Process: nozzle_diameter is a scalar "0.4", not a CSV
    assert p["nozzle_diameter"] == "0.4"
    assert p["layer_height"] == "0.16"
    # Filament: real nozzle temp (255), not the range_low (230)
    assert f["nozzle_temperature"] == ["255"]
    assert f["filament_vendor"] == ["SUNLU"]
    # Name doesn't have stray quote chars
    assert '"' not in f["name"]
    assert '"' not in p["name"]
    # bed_type mirrored from curr_bed_type so Orca knows the plate
    assert f["bed_type"] == ["Textured PEI Plate"]
