"""Test upload gate logic — fail-closed on bad state, parse metadata correctly.

upload_gcode is the second-most safety-critical script (after toolmap).
A regression that bypasses gates here = uploading a job to an actively-
printing machine, or uploading without verifying the target material.
"""
from __future__ import annotations

from pathlib import Path

import pytest

import u1_upload_gcode


def _idle_status():
    return {
        "print_stats": {"state": "standby", "filename": "", "info": {}},
        "virtual_sdcard": {"is_active": False},
        "webhooks": {"state": "ready"},
        "pause_resume": {"is_paused": False},
        "heater_bed": {"target": 0},
        "extruder": {"target": 0},
        "extruder1": {"target": 0},
        "extruder2": {"target": 0},
        "extruder3": {"target": 0},
    }


def test_idle_printer_passes():
    blockers = u1_upload_gcode.ensure_idle_ready(_idle_status())
    assert blockers == []


def test_active_print_blocks_upload():
    """If the printer is actively printing, ensure_idle_ready returns blockers."""
    s = _idle_status()
    s["virtual_sdcard"]["is_active"] = True
    s["print_stats"]["filename"] = "current.gcode"
    blockers = u1_upload_gcode.ensure_idle_ready(s)
    assert any("virtual_sdcard is active" in b for b in blockers), blockers


def test_paused_print_blocks_upload():
    s = _idle_status()
    s["pause_resume"]["is_paused"] = True
    blockers = u1_upload_gcode.ensure_idle_ready(s)
    assert any("paused" in b for b in blockers), blockers


def test_active_print_state_blocks_upload():
    s = _idle_status()
    s["print_stats"]["state"] = "printing"
    blockers = u1_upload_gcode.ensure_idle_ready(s)
    assert any("print_stats state" in b for b in blockers), blockers


def test_webhooks_not_ready_blocks_upload():
    s = _idle_status()
    s["webhooks"]["state"] = "shutdown"
    s["webhooks"]["state_message"] = "test shutdown"
    blockers = u1_upload_gcode.ensure_idle_ready(s)
    assert any("webhooks state" in b for b in blockers), blockers


def test_hot_extruder_blocks_upload():
    """Target temperature > 0 on any heater is a blocker — printer isn't truly idle."""
    s = _idle_status()
    s["extruder1"]["target"] = 240
    blockers = u1_upload_gcode.ensure_idle_ready(s)
    assert any("extruder1 target is non-zero" in b for b in blockers), blockers


# ---------- parse_gcode_metadata ----------

SAMPLE_GCODE = b"""; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-06-21 at 12:00:00
; HEADER_BLOCK_END

; filament_type = PETG
; layer_height = 0.20
; first_layer_temperature = 240
; bed_temperature = 80
; print_settings_id = Community 0.20 Strength @Snapmaker U1 Textured PEI
; filament_settings_id = Community Generic PETG @Snapmaker U1 Textured PEI
; nozzle_diameter = 0.4
; estimated printing time (normal mode) = 5h 56m

T1
M104 S240
M140 S80

G28
G1 X100 Y100 Z5 F3000
"""


def test_parse_gcode_metadata_extracts_key_fields(tmp_path):
    gcode = tmp_path / "test.gcode"
    gcode.write_bytes(SAMPLE_GCODE)
    info = u1_upload_gcode.parse_gcode_metadata(gcode)
    assert info["metadata"]["filament_type"] == "PETG"
    assert info["metadata"]["layer_height"] == "0.20"
    assert "Community" in info["metadata"]["print_settings_id"]


def test_parse_gcode_metadata_detects_intended_tool_T1(tmp_path):
    """T1 in startup → intended_tool = extruder1."""
    gcode = tmp_path / "test.gcode"
    gcode.write_bytes(SAMPLE_GCODE)
    info = u1_upload_gcode.parse_gcode_metadata(gcode)
    assert info["intended_tool"] == "extruder1"


def test_parse_gcode_metadata_defaults_T0_to_extruder(tmp_path):
    """No T command (or T0) → intended_tool = 'extruder' (zero-indexed default)."""
    g = SAMPLE_GCODE.replace(b"T1\n", b"")
    gcode = tmp_path / "test.gcode"
    gcode.write_bytes(g)
    info = u1_upload_gcode.parse_gcode_metadata(gcode)
    assert info["intended_tool"] == "extruder"


def test_parse_gcode_metadata_handles_huge_files(tmp_path):
    """Mid-file noise outside the 512KB head/tail window mustn't crash parsing."""
    g = SAMPLE_GCODE + b"\n" + (b"G1 X1 Y1\n" * 100_000) + b"\n; trailing_meta = ignored\n"
    gcode = tmp_path / "huge.gcode"
    gcode.write_bytes(g)
    info = u1_upload_gcode.parse_gcode_metadata(gcode)
    assert info["metadata"]["filament_type"] == "PETG"  # head still parsed cleanly


# ---------- regression: prefix-collision + quote-strip ----------

REAL_META_GCODE = b"""; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4
; HEADER_BLOCK_END

; nozzle_temperature = 255
; nozzle_temperature_initial_layer = 255
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 230
; filament_settings_id = "Hermes Generic PETG @Snapmaker U1 Textured PEI"
; filament_type = PETG
; first_layer_bed_temperature = 80
; bed_temperature = 80
; print_settings_id = Hermes 0.16 Optimal @Snapmaker U1 Textured PEI
; printer_settings_id = Snapmaker U1 (0.4 nozzle)

T1
G28
"""


def test_parse_does_not_swallow_longer_key(tmp_path):
    """Regression: nozzle_temperature must NOT be overwritten by
    nozzle_temperature_range_low via prefix match."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_META_GCODE)
    info = u1_upload_gcode.parse_gcode_metadata(g)
    assert info["metadata"]["nozzle_temperature"] == "255"


def test_parse_strips_orca_value_quotes(tmp_path):
    """Regression: literal `"` chars around quoted values must be stripped."""
    g = tmp_path / "real.gcode"
    g.write_bytes(REAL_META_GCODE)
    info = u1_upload_gcode.parse_gcode_metadata(g)
    assert '"' not in info["metadata"]["filament_settings_id"]
    assert info["metadata"]["filament_settings_id"].startswith("Hermes Generic PETG")


# ---------- --stl thumbnail wiring (opt-in) ----------

def test_inject_thumbnail_missing_stl_fails_closed(tmp_path):
    """If the operator passed --stl but the file doesn't exist, return failure."""
    g = tmp_path / "x.gcode"
    g.write_text("G28\n")
    ok, detail = u1_upload_gcode.inject_thumbnail(tmp_path / "nope.stl", g)
    assert ok is False
    assert "STL not found" in detail


def test_inject_thumbnail_missing_injector_fails_closed(tmp_path, monkeypatch):
    """If tools/gcode_inject_thumbnail.py is missing, surface that — don't
    silently upload without a thumbnail."""
    g = tmp_path / "x.gcode"
    g.write_text("G28\n")
    stl = tmp_path / "x.stl"
    stl.write_bytes(b"\x00" * 84 + b"\x00\x00\x00\x00")  # 0-triangle binary STL

    # Monkey-patch __file__ so the helper computes a tools/ path that doesn't exist.
    monkeypatch.setattr(u1_upload_gcode, "__file__", str(tmp_path / "scripts" / "u1_upload_gcode.py"))
    ok, detail = u1_upload_gcode.inject_thumbnail(stl, g)
    assert ok is False
    assert "injector not found" in detail


def test_inject_thumbnail_happy_path_uses_real_injector(tmp_path):
    """End-to-end: real STL + real injector → returns ok and G-code gets blocks."""
    pytest.importorskip("PIL")
    pytest.importorskip("numpy")

    import struct
    # Tiny one-triangle binary STL
    stl_bytes = (
        b"\x00" * 80 + struct.pack("<I", 1) +
        struct.pack("<3f", 0, 0, 1) +     # normal
        struct.pack("<3f", 0, 0, 0) +     # v0
        struct.pack("<3f", 10, 0, 0) +    # v1
        struct.pack("<3f", 5, 10, 0) +    # v2
        struct.pack("<H", 0)              # attr
    )
    stl = tmp_path / "tri.stl"
    stl.write_bytes(stl_bytes)
    g = tmp_path / "x.gcode"
    g.write_text("; generated by Snapmaker Orca 2.3.4\n; HEADER_BLOCK_START\nG28\n")

    ok, _ = u1_upload_gcode.inject_thumbnail(stl, g, sizes="48x48")
    assert ok is True
    body = g.read_text()
    assert "thumbnail begin 48x48" in body
    assert "thumbnail end" in body


# ---------- Upload transport (v2.4.1) ----------
# First real Windows upload (2026-07-12): the multipart POST hit a connect
# timeout that escaped as a bare traceback and generic rc=1, with nothing
# recorded about the URL tried or how long it waited. The transport layer
# had zero test coverage. These tests use a local stub server / closed
# port - never a real printer.

import json
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer


def _stub_moonraker(captured):
    class H(BaseHTTPRequestHandler):
        def do_POST(self):
            captured["path"] = self.path
            captured["body"] = self.rfile.read(
                int(self.headers.get("Content-Length", 0)))
            captured["ctype"] = self.headers.get("Content-Type", "")
            payload = json.dumps({"result": {"item": {"path": "x.gcode"}}})
            self.send_response(201)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload.encode())

        def log_message(self, *a):
            pass

    srv = HTTPServer(("127.0.0.1", 0), H)
    t = threading.Thread(target=srv.serve_forever, daemon=True)
    t.start()
    return srv


def test_multipart_upload_shape_against_stub_server(tmp_path):
    captured = {}
    srv = _stub_moonraker(captured)
    try:
        gcode = tmp_path / "part plate1.gcode"
        gcode.write_bytes(b"; gcode body\nG28\n")
        url = f"http://127.0.0.1:{srv.server_address[1]}/server/files/upload"
        resp = u1_upload_gcode.multipart_upload(
            url, {"root": "gcodes", "path": "", "print": "false"},
            "file", gcode)
        assert resp["result"]["item"]["path"] == "x.gcode"
        assert captured["path"] == "/server/files/upload"
        body = captured["body"]
        assert b'name="root"' in body and b"gcodes" in body
        assert b'name="print"' in body and b"false" in body
        assert b'filename="part plate1.gcode"' in body
        assert b"G28" in body, "file bytes must ride in the multipart body"
        assert captured["ctype"].startswith("multipart/form-data; boundary=")
    finally:
        srv.shutdown()


def test_multipart_upload_raises_promptly_on_dead_port(tmp_path):
    import socket
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()  # nothing listens here now
    gcode = tmp_path / "x.gcode"
    gcode.write_bytes(b"G28\n")
    with pytest.raises(Exception):
        u1_upload_gcode.multipart_upload(
            f"http://127.0.0.1:{port}/server/files/upload",
            {"root": "gcodes"}, "file", gcode, timeout=3)


def test_transport_failure_maps_to_rc4_with_diagnostics(tmp_path, monkeypatch,
                                                        mock_http,
                                                        moonraker_responses,
                                                        capsys):
    """A transport exception during the POST must return the contract's
    rc=4 and write the granular artifact with the URL tried, the exception
    class, and elapsed time - not escape as a traceback and rc=1."""
    gcode = tmp_path / "part_plate1.gcode"
    gcode.write_text(
        "; printer_settings_id = Snapmaker U1 (0.4 nozzle)\n"
        "; filament_type = PETG\n"
        "; nozzle_temperature = 245\n"
        "; first_layer_bed_temperature = 70\n"
        "G28\n")
    moonraker_responses["/server/files/metadata"] = {"error": "not found"}
    moonraker_responses["/server/files/list"] = {"result": []}

    def _boom(*a, **kw):
        raise TimeoutError("connect timed out")

    monkeypatch.setattr(u1_upload_gcode, "multipart_upload", _boom)
    monkeypatch.setenv("SNAPMAKER_U1_HOST", "192.0.2.1")
    import sys as _sys
    monkeypatch.setattr(_sys, "argv",
                        ["u1_upload_gcode.py", str(gcode), "--material", "PETG"])
    rc = u1_upload_gcode.main()
    assert rc == 4, capsys.readouterr().out[-800:]
    out = capsys.readouterr().out
    assert "transport error" in out
    from u1_config import get_data_dir
    art = json.loads((get_data_dir() / "latest_upload_result.json").read_text())
    assert art["moonraker_upload_ok"] is False
    assert "TimeoutError" in art["transport_error"]
    assert art["upload_url"].startswith("http://192.0.2.1")
    assert "elapsed_s" in art
