#!/usr/bin/env python3
"""Inject PrusaSlicer/Orca-compatible thumbnail blocks into a sliced G-code.

OrcaSlicer's CLI doesn't render thumbnails (GUI-only code path), so even
though the sliced G-code declares `; thumbnails = 48x48/PNG, 300x300/PNG`,
the actual `; thumbnail begin ... end` blocks are missing. Snapmaker's app +
Moonraker parse those blocks to show a preview; without them, you get a
generic file icon.

This script does what the GUI would have done:
  1. Parse the STL (binary or ASCII)
  2. Project to 2D using an isometric-ish orthographic projection
  3. Render with PIL — flat Lambertian shading per face, painter's algorithm
  4. Encode PNG → base64
  5. Splice `; thumbnail begin W x H N\\n; <b64>\\n; thumbnail end` blocks
     into the G-code header

Requires: PIL (Pillow) + numpy. Pure stdlib otherwise.

Example:
    python3 tools/gcode_inject_thumbnail.py \\
        --stl model.stl --gcode plate_1.gcode \\
        --sizes 48x48,300x300 --in-place
"""
from __future__ import annotations

import argparse
import base64
import io
import re
import sys
from pathlib import Path
from typing import Iterable

# Make sibling tools/ importable when run as a script.
sys.path.insert(0, str(Path(__file__).resolve().parent))

import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402

# Shared STL parsing + isometric Lambertian render. The thumbnail injector
# only needs the single-view 'iso' render; the orientation renderer reuses
# more of the same primitives. See tools/_stl_render.py.
from _stl_render import (  # noqa: E402
    _is_ascii_stl,
    _iso_rotation,
    _parse_ascii_stl,
    _parse_binary_stl,
    parse_stl,
    render,
)


# ---------- G-code splicing ----------

# Match an existing `; thumbnail begin ... ; thumbnail end` block (any width).
_BLOCK_RE = re.compile(
    r"^;\s*thumbnail\s+begin\b.*?^;\s*thumbnail\s+end\s*$\n?",
    re.MULTILINE | re.DOTALL | re.IGNORECASE,
)


def encode_thumbnail_block(img: Image.Image) -> str:
    """Encode `img` as a PrusaSlicer/Orca thumbnail block string."""
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    png_bytes = buf.getvalue()
    b64 = base64.b64encode(png_bytes).decode("ascii")
    # PrusaSlicer convention: third number = length of base64 string (no whitespace).
    header = f"; thumbnail begin {img.width}x{img.height} {len(b64)}\n"
    chunks = [b64[i:i + 78] for i in range(0, len(b64), 78)]
    body = "".join(f"; {chunk}\n" for chunk in chunks)
    return f";\n{header}{body}; thumbnail end\n;\n"


def splice_blocks(gcode_text: str, blocks: Iterable[str]) -> str:
    """Insert/replace thumbnail blocks in `gcode_text`. Idempotent."""
    # Strip any existing thumbnail blocks first.
    cleaned = _BLOCK_RE.sub("", gcode_text)
    payload = "".join(blocks)

    # Inject before first meaningful G-code marker. Order of preference:
    #   1) before `; HEADER_BLOCK_START` (Orca convention)
    #   2) after the leading `; generated by` line if present
    #   3) at the very top
    marker = "; HEADER_BLOCK_START"
    idx = cleaned.find(marker)
    if idx != -1:
        return cleaned[:idx] + payload + cleaned[idx:]
    lines = cleaned.splitlines(keepends=True)
    insert_at = 0
    for i, line in enumerate(lines):
        if line.lstrip().lower().startswith("; generated by"):
            insert_at = i + 1
            break
    return "".join(lines[:insert_at]) + payload + "".join(lines[insert_at:])


# ---------- CLI ----------

def _parse_sizes(spec: str) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "x" not in chunk.lower():
            raise ValueError(f"size {chunk!r} must look like 300x300")
        w, h = chunk.lower().split("x", 1)
        out.append((int(w), int(h)))
    if not out:
        raise ValueError("no sizes parsed")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--stl", type=Path, required=True, help="Source STL (binary or ASCII).")
    ap.add_argument("--gcode", type=Path, required=True, help="G-code to inject into.")
    ap.add_argument("--sizes", default="48x48,300x300",
                    help="Comma-separated WxH list. Default: 48x48,300x300 (Snapmaker U1 default).")
    ap.add_argument("--in-place", action="store_true",
                    help="Overwrite the G-code in place (default: write to <gcode>.thumb.gcode).")
    ap.add_argument("--output", type=Path, default=None,
                    help="Explicit output path (overrides --in-place behaviour).")
    args = ap.parse_args(argv)

    if not args.stl.exists():
        print(f"STL not found: {args.stl}", file=sys.stderr)
        return 2
    if not args.gcode.exists():
        print(f"G-code not found: {args.gcode}", file=sys.stderr)
        return 2

    try:
        sizes = _parse_sizes(args.sizes)
    except ValueError as e:
        print(f"--sizes: {e}", file=sys.stderr)
        return 2

    tris = parse_stl(args.stl)
    if tris.shape[0] == 0:
        print(f"STL has no triangles: {args.stl}", file=sys.stderr)
        return 3

    blocks = [encode_thumbnail_block(render(tris, w, h)) for w, h in sizes]

    gcode_text = args.gcode.read_text(encoding="utf-8", errors="replace")
    new_text = splice_blocks(gcode_text, blocks)

    if args.output is not None:
        out_path = args.output
    elif args.in_place:
        out_path = args.gcode
    else:
        # `<name>.thumb.gcode` reads better than `<name>.gcode.thumb`
        out_path = args.gcode.with_name(args.gcode.stem + ".thumb" + args.gcode.suffix)

    out_path.write_text(new_text, encoding="utf-8")
    print(f"Injected {len(sizes)} thumbnail block(s): "
          f"{', '.join(f'{w}x{h}' for w, h in sizes)} → {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
